// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestBancoPichincha.Api.Movimientos.Persistencia;

namespace TestBancoPichincha.Api.Movimientos.Migrations
{
    [DbContext(typeof(ContextoMovimiento))]
    [Migration("20220314150403_MigracionPostgresInicial")]
    partial class MigracionPostgresInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TestBancoPichincha.Api.Movimientos.Modelo.Movimiento", b =>
                {
                    b.Property<string>("MovimientoId")
                        .HasColumnType("text");

                    b.Property<Guid?>("CuentaId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Fecha")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone")
                        .HasMaxLength(10);

                    b.Property<double>("Saldo")
                        .HasColumnType("double precision");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<double>("Valor")
                        .HasColumnType("double precision");

                    b.HasKey("MovimientoId");

                    b.ToTable("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
