// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestBancoPichincha.Api.Cuenta.Persistencia;

namespace TestBancoPichincha.Api.Cuenta.Migrations
{
    [DbContext(typeof(ContextoCuenta))]
    [Migration("20220314150349_MigracionPostgresInicial")]
    partial class MigracionPostgresInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TestBancoPichincha.Api.Cuenta.Modelo.CuentaBanco", b =>
                {
                    b.Property<string>("CuentaId")
                        .HasColumnType("text");

                    b.Property<Guid?>("ClienteId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<double>("SaldoInicial")
                        .HasColumnType("double precision");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.HasKey("CuentaId");

                    b.ToTable("Cuentas");
                });
#pragma warning restore 612, 618
        }
    }
}
